<?php
/**
 * Fontis New Zealand Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Newzealand
 * @author     Chris Norton
 * @copyright  Copyright (c) 2008 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<p><?=$this->getMethod()->getTitle()?>
<?if($this->getInfo()->getAdditionalData()):?>
    <?if($this->getAccountName()):?><br /><?=$this->__('Payee: %s', $this->getAccountName())?><?endif;?>
	<?if($this->getAccountBank()):?><br /><?=$this->__('Bank: %s', $this->getAccountBank())?><?endif;?>
	<?if($this->getAccountNumber()):?><br /><?=$this->__('ACC#: %s', $this->getAccountNumber())?><?endif;?>
	<?if($this->getAccountBranch()):?><br /><?=$this->__('Branch: %s', $this->getAccountBranch())?><?endif;?>
<?endif;?>
</p>
