<?php
/**
 * Fontis New Zealand Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Fontis
 * @package    Fontis_Newzealand
 * @author     Chris Norton
 * @copyright  Copyright (c) 2008 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<fieldset class="form-list">
    <ul id="payment_form_<?=$this->getMethodCode()?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getAccountName()):?>
                    <?=$this->__('<label>Payee</label>: %s', $this->getMethod()->getAccountName())?><br />
                <?php endif;?>
                <?php if ($this->getMethod()->getAccountBank()):?>
                    <?=$this->__('<label>Bank</label>: %s', $this->getMethod()->getAccountBank())?><br />
                <?php endif;?>
                <?php if ($this->getMethod()->getAccountNumber()):?>
                    <?=$this->__('<label>ACC#</label>: %s', $this->getMethod()->getAccountNumber())?><br />
                <?php endif;?>
                <?php if ($this->getMethod()->getAccountBranch()):?>
                    <?=$this->__('<label>Branch</label>: %s', $this->getMethod()->getAccountBranch())?><br />
                <?php endif;?>
                <?php if ($this->getMethod()->getMessage()):?>
                    <p><?=$this->__('%s', $this->getMethod()->getMessage());?></p>
                <?php endif;?>
            </div>
        </li>
    </ul>
</fieldset>
